### ISSUE TITLE
repository

### ISSUE THREAD

**Issue by Eljah** [ashri/java-wordpress-api#1]
Hi Ashri, is java-wordpres-api dependency in the Central Maven repo? I have added the dependencies according to your page, but the dependency is not available...

**Comment by ashri** [comment]
Hi Eljah,

I had not posted the library to Maven Central however I have now added a 1.0 release of the library to the mvn-repo branch of this repository. I have updated the README file to document how to use Github as a repository to add the library as a dependency. Hope that works for you.

Thanks

**Comment by Eljah** [comment]
thank you!
